### ISSUE TITLE
论文首页 学号和密级未对齐

### ISSUE THREAD

**Issue by yhshu** [Acytoo/neu_bachelor_thesis_template#3]
如图所示。论文首页的学号和密级未对齐，采用 overleaf 编译。

![image](https://user-images.githubusercontent.com/21468340/70585636-bfff2000-1bff-11ea-96f5-58e4c4a7312d.png)

**Comment by yhshu** [comment]
一种解决方法：使用注释中的学号和密级即可，即
`\heiti\zihao{5}学号\rule[-4pt]{3cm}{0.05em} \hspace{5.5cm} 密级\rule[-4pt]{3cm}{0.05em}`

**Comment by Acytoo** [comment]
关于学号与密级不在同一行，当时我问了几个老师，得到的比较靠谱的回答是：学校在存档时，会贴一张封条，盖住学号而留下密级，所以这两个没有设计在同一行。

然后就将在同一行的代码注释了，改为现在的样子。

如果你是东大的学生，那么你不用担心这个问题，因为在交论文时，会发给你学校制作的封皮，自己打印的这张封皮，用不上。（19年时，学校发的封皮，学号与密级也没有在同一行）

**Comment by yhshu** [comment]
原来有这个原因，可能是因为盲审。多谢。
